week 3 assessment completed
learn-academy-2022-charlie/week-3-assessment-OnyxFire1 pull request #1
Opened 2022-05-31 05:19 UTC by OnyxFire1

# Submitting Week 2 Assessment

### ✅ Completed Files
Mark the following as confirmation that the files in this repository are complete.
- [ ] Coding Challenges
- [ ] Interview Questions
- [ ] React Debugging

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:

2022-05-31 05:21 UTC, OnyxFire1 commented
I had trouble with creating the test for #2 and #3 to get a pass. I did not complete either one but will try to get it done before the next assessment, if able. This is just a continuation of my struggles grasping the information.

2022-05-31 18:26 UTC, WalkerTexas-coder requested changes
Submit some code for this assessment and I will finish reviewing your PR! Great work on #1. Keep using your ability to problem solve and you will get this!

2022-05-31 18:26 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +// //PASS ./code-challenges.test.js
This is excellent! It's very clear what is taking place. Good work!

2022-06-03 16:03 UTC, WalkerTexas-coder requested changes
Missing pseudo code for #3

2022-06-03 16:03 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +    return arr.map((sum => value => sum += value)(0));
You are missing pseudo code for how this function works.

2022-06-03 20:48 UTC, WalkerTexas-coder approved these changes

2022-06-03 20:48 UTC, WalkerTexas-coder commented on code-challenges.test.js
> +// I'm not sure if this makes sense, trying to explain it the best way I can. I did get help from my tutor.
Sounds good

2022-06-03 20:52 UTC, merged